services:
  juiceshop:
    image: bkimminich/juice-shop
    container_name: juiceshop
    restart: unless-stopped
    networks:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: rev_proxy
    restart: unless-stopped
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx

  wazuh-agent:
    image: wazuh/wazuh-agent:4.14.6
    container_name: wazuh-agent
    restart: unless-stopped
    networks:
      - siem-net
    volumes:
      - nginx_logs:/var/log/nginx:ro
    environment:
      - WAZUH_MANAGER_SERVER=wazuh.manager
      - WAZUH_REGISTRATION_SERVER=wazuh.manager
      - WAZUH_AGENT_NAME=juiceshop-nginx

networks:
  backend:
    internal: true
  frontend:
  siem-net:
    external: true

volumes:
  nginx_logs:
